services:

  product-service:
    build: ./product-service
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=product-service
    ports:
      - "8081:8081"

  order-service:
    build: ./order-service
    environment:
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=order-service
    ports:
      - "8082:8082"

